version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: nexus
    main: ./
    binary: nexus
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else }}{{ .Arch }}{{ end }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: checksums.txt

changelog:
  use: github
